# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.Evento', verbose_name='Eventos frecuentes'),
        ),
    ]
