# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-09 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citas', '0002_auto_20170509_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
