# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-09 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('ventas', '0001_initial'),
        ('configuracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunacion',
            name='vacuna',
            field=models.ManyToManyField(blank=True, max_length=100, to='ventas.Producto'),
        ),
        migrations.AddField(
            model_name='notas',
            name='atenciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Atenciones'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='color',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='raza', chained_model_field='raza', on_delete=django.db.models.deletion.CASCADE, to='configuracion.Color'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='clinica.Cliente'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='especie',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='especie', to='configuracion.Especie'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='especie', chained_model_field='especie', on_delete=django.db.models.deletion.CASCADE, to='configuracion.Raza'),
        ),
        migrations.AddField(
            model_name='historial',
            name='mascota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota', verbose_name='Mascota'),
        ),
        migrations.AddField(
            model_name='historial',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colamedica',
            name='mascota',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Mascota'),
        ),
        migrations.AddField(
            model_name='colamedica',
            name='medico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='params.Person'),
        ),
        migrations.AddField(
            model_name='atenciones',
            name='colamedica',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ColaMedica', unique=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='atenciones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.Atenciones'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='diagnostico',
            field=models.ManyToManyField(max_length=300, to='clinica.Diagnostico'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='hallasgos_clinicos',
            field=models.ManyToManyField(max_length=300, to='clinica.HallasgosClinicos'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='pruebas_auxiliares',
            field=models.ManyToManyField(max_length=300, to='clinica.Pruebas'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tratamiento',
            field=models.ManyToManyField(max_length=300, to='clinica.Tratamiento'),
        ),
    ]
