# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-17 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20170509_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='atenciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.Atenciones'),
        ),
    ]
