# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20170517_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='ndescripcion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='colamedica',
            name='estado',
        ),
        migrations.AddField(
            model_name='colamedica',
            name='hora',
            field=models.TimeField(auto_now_add=True, default='12:02:01', verbose_name='Hora Registrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colamedica',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='colamedica',
            name='is_actived',
            field=models.BooleanField(default=False, verbose_name='Actived'),
        ),
        migrations.AddField(
            model_name='notas',
            name='created_time',
            field=models.TimeField(auto_now_add=True, default='10:10:03', verbose_name='Hora Creada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notas',
            name='created_ath',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Creada'),
        ),
    ]
