# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-13 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_auto_20170530_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciones',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
