# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_atenciones_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='vobservacion',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='motivo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='observacion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='tipo_vacunación',
            field=models.CharField(blank=True, choices=[('cita', 'cita'), ('consulta', 'consulta')], max_length=50),
        ),
    ]
