# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_auto_20170614_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='fecha_programada',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='created_ath',
            field=models.DateTimeField(auto_now_add=True, default='2012-12-12', verbose_name='Fecha Creada'),
            preserve_default=False,
        ),
    ]
