# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-14 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_auto_20170614_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacunacion',
            name='dosis',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
