# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_auto_20170614_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciones',
            name='archivo',
            field=models.FileField(default=1, upload_to='Archivos', verbose_name='Archivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='atenciones',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.Atenciones'),
        ),
    ]
