# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0013_auto_20170615_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivosadjuntos',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivosadjuntos',
            name='file',
            field=models.FileField(default=1, upload_to='/home/rusbel/2017/Desarrollo/Django/CLIVET/media'),
            preserve_default=False,
        ),
    ]
