# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0014_auto_20170615_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivosadjuntos',
            name='atenciones',
        ),
        migrations.AddField(
            model_name='archivosadjuntos',
            name='atenciones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinica.Atenciones'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivosadjuntos',
            name='file',
            field=models.FileField(upload_to='/home/rusbel/Projects/clivet/CLIVET/media'),
        ),
    ]
