# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0015_auto_20170615_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosadjuntos',
            name='file',
            field=models.FileField(upload_to='archivos'),
        ),
    ]
