# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-16 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0017_auto_20170616_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacunacion',
            name='tipo_vacunación',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='tipo_vacunacion',
            field=models.CharField(blank=True, choices=[('cita', 'cita'), ('consulta', 'consulta')], max_length=50, verbose_name='Tipo Vacunación'),
        ),
    ]
