# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-18 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0018_auto_20170616_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colamedica',
            options={'permissions': (('colamedica', 'Can ALL colamedica'),), 'verbose_name': 'Cola Medica', 'verbose_name_plural': 'Colas Medicas'},
        ),
    ]
