# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-18 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0020_auto_20170618_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('cliente', 'Can ALL cliente'), ('cliente', 'Can CREATE cliente'), ('cliente', 'Can DELETE cliente'), ('cliente', 'Can UPDATE cliente'), ('cliente', 'Can LIST cliente')), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
