# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Colores',
                'verbose_name': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Especies',
                'verbose_name': 'Especie',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_especie', to='configuracion.Especie')),
            ],
            options={
                'verbose_name_plural': 'Razas',
                'verbose_name': 'Raza',
            },
        ),
        migrations.AddField(
            model_name='color',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_color_especie', to='configuracion.Especie'),
        ),
        migrations.AddField(
            model_name='color',
            name='raza',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='especie', chained_model_field='especie', on_delete=django.db.models.deletion.CASCADE, to='configuracion.Raza'),
        ),
    ]
