# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-28 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antiparasitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_actived', models.BooleanField(default=False, verbose_name='Actived')),
                ('especie', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Especie')),
            ],
            options={
                'verbose_name': 'Antiparasitarios',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(max_length=300, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_actived', models.BooleanField(default=False, verbose_name='Actived')),
            ],
            options={
                'verbose_name': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Vacunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_actived', models.BooleanField(default=False, verbose_name='Actived')),
                ('especie', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Especie')),
            ],
            options={
                'verbose_name': 'Vacunas',
            },
        ),
    ]
