# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-26 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20170509_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'permissions': (('compra', 'Can ALL compra'),), 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'permissions': (('detallecompra', 'Can ALL detallecompra'),), 'verbose_name': 'Detalle Compra', 'verbose_name_plural': 'Detalles Compra'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'permissions': (('proveedor', 'Can ALL proveedor'),), 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
