# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acopios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acopio',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total'),
        ),
    ]
