# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-16 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='codigo',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
