# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-18 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': (('ventas', 'Can ALL ventas'),), 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
