# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-26 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20170618_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_venta',
            options={'permissions': (('detalle_venta', 'Can ALL detalle_venta'),), 'verbose_name': 'Detalle Venta', 'verbose_name_plural': 'Detalles Venta'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('producto', 'Can ALL producto'),), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
