# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-11-30 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_producto_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
